name: literasi_akhlak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  http: ^1.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  vsc_quill_delta_to_html: ^1.0.5  # Use ^1.0.5 as suggested, or check pub.dev for the latest

dependency_overrides:
  intl: ^0.20.2  # Pastikan override ini konsisten

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/asset1.png
    - assets/images/asset2.png
    - assets/images/asset3.png